name: build

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: true
            matrix:
                config:
                    - name: linux
                      arch: x86-64
                      os: ubuntu-18.04
                      target: x86_64-unknown-linux-gnu
                      artifact_suffix: ""
#                    - name: windows
#                      arch: x86-64
#                      os: windows-latest
#                      target: x86_64-pc-windows-msvc
#                      artifact_suffix: ".exe"
                    - name: macos
                      arch: x86-64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_suffix: ""
                    - name: macos
                      arch: arm64
                      os: macos-11
                      target: aarch64-apple-darwin
                      artifact_suffix: ""

        name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
        runs-on: ${{ matrix.config.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  target: ${{ matrix.config.target }}
                  default: true

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release --target ${{ matrix.config.target }}

            - name: Publish
              uses: actions/upload-artifact@v2
              with:
                  name: ipfs-webdav_${{ matrix.config.name }}-${{ matrix.config.arch }}${{ matrix.config.artifact_suffix }}
                  path: target/${{ matrix.config.target }}/release/ipfs-webdav${{ matrix.config.artifact_suffix }}
